config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    collection { post :import }
    collection { post :starclick }
  end

  root "orders#index"

  get '/starclick' => 'orders#starclick', as: 'starclick'
  get '/ms2n' => 'orders#ms2n', as: 'ms2n'
  get '/download' => 'orders#download', as: 'download'
  

end

app/models/order.rb
class Order < ActiveRecord::Base

	require 'csv'
	require 'roo'
	require 'open-uri'
	require 'json'
	require 'pp'

	:flash_notice

	# Manual Ways Export Excel

	def self.to_csv(options = {})
	  	CSV.generate(options) do |csv|
	    	csv << ["SC", "Tanggal Order", "NCLI", "Pelanggan", "Alamat", "NDInet", "NDVoice", "Witel", "STO", "ODP", "Status", "Status Message", "K-Kontak", "Inputer", "Tipe Transaksi", "VA"]
	    	all.each do |product|
	      		csv << product.attributes.values_at("sc", "orderdate", "ncli", "customer", "address", "nd_internet", "nd_voice", "witel", "sto", "odp", "status", "status_message", "k_contact", "inputer", "transaction_type", "status_va")
	    	end
	  	end
	end


	# Roo Ways Import Excel

	def import
	  Order.import(params[:file])
	  redirect_to root_url, notice: "decorations imported."
	end

	def self.import(file)
	  	spreadsheet = Roo::Spreadsheet.open(file.path)
	  	#header = spreadsheet.row(1)
	  	#(2..spreadsheet.last_row).each do |i|
	  	spreadsheet.each do |row|
	    	# rows = Hash[[header, spreadsheet.row(i)].transpose]
	    	# product = User.find_by(id: rows["id"]) || new
	    	# product.attributes = rows.to_hash
	    	product.sc = row[0]
			product.orderDate = row[1]
			product.ncli = row[4]
			product.customer = row[5]
			product.address = row[6]
			product.ndInternet = row[9]
			product.ndVoice = row[10]
			product.status = row[11]
			product.statusMessage = row[12]
			product.odp = row[13]
			product.witel = row[14]
			product.kContact = row[15]
			product.inputer = row[16]
			product.transactionType = row[17]
			product.serviceType = row[18]
			product.sto = row[19]

			# checkin SC function
			#	# if exist, Skip
			# checkin Status SC function
			#	# if it changes, Update! 

			if product.sc != "No. SC"
				if Order.find_by(sc: product.sc)
	    			#unless User.where(user: product.user, steps: product.steps)
	    			#id = User.where (user: product.user).select("id").first
	    			id = Order.where(sc: product.sc).select("id").first
	    			status = Order.where(sc: product.sc).select("status").first
	    			if status != product.status
	    				Order.update(id, status: product.status)
	    				Order.update(id, statusMessage: product.statusMessage)
	    			else
	    				next
	    			end
	    		else
	    			product.save
	    		end
	    	end

	  	end
	end

	def self.open_spreadsheet(file)
	  	case File.extname(file.original_filename)
	  	when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
	  	when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
	  	when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
	  	else raise "Unknown file type: #{file.original_filename}"
	  	end
	end

	def self.starclick

		request_uri = 'https://starclick.telkom.co.id/noss_prod/data/get_order.php?_dc=1471594704134&SearchText=kalteng&Field=ORG&Fieldstatus=&Fieldwitel=&StartDate=&EndDate=&page=1&start=0&limit=5'
      	request_query = ''
      	url = "#{request_uri}#{request_query}"

      	buffer = open(url).read

      	result = JSON.parse(buffer)

      	data = result["order"]

      	data.each do |row| 	
	      	product = Order.new

			product.sc = row["orderId"]
			product.orderDate = row["orderDate"]
			product.ncli = row["orderNcli"]
			product.customer = row["orderName"]
			product.address = row["orderAddr"]
			product.ndInternet = row["ndemSpeedy"]
			product.ndVoice = row["ndemPots"]
			product.status = row["orderStatus"]
			product.statusMessage = row["orderPaket"]
			product.odp = row["alproName"]
			product.witel = row["orderPlasa"]
			product.kContact = row["kcontact"]
			product.inputer = row["username"]
			product.transactionType = row["jenisPsb"]
			product.sto = row["sto"]

			if Order.find_by(sc: product.sc)
	    		id = Order.where(sc: product.sc).select("id").first
	    		status = Order.where(sc: product.sc).select("status").first
	    		if status != product.status
	    			Order.update(id, status: product.status)
	    			Order.update(id, statusMessage: product.statusMessage)
	    			update += 1
	    		else
	    			next
	    		end
	    	else
	    		baru += 1
	    		product.save
	    	end
		end
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	require 'open-uri'
	require 'json'
	require 'pp'
	require 'nokogiri'


	def index
		if Order.exists?
			@orders = Order.order(:sc)
			plk = ['KKN','KKP','PLK','PPS','PYM']
			pbu = ['KMI','SUA','PBU']
			sai = ['KPB','SAI']
			mtw = ['AMP','PRC','BNT','TML','MTW']
			@sto = [plk,'KKN','KKP','PLK','PPS','PYM',pbu,'KMI','SUA','PBU',sai,'KPB','SAI',mtw,'AMP','PRC','BNT','TML','MTW',plk+pbu+sai+mtw]
			@statuses = ['UN-SCC','CANCEL COMPLETED','Process SC (Pre Registered)','Process SOA (Registered)','Process ISISKA (VA)','Process ISISKA','Process OSS (Created)','Process OSS (Cancel)','Process OSS (Provision Designed)','Fallout (Data)','Process OSS (Provision Issued)','Fallout (WFM)','Process OSS (Activation Completed)','Fallout (Activation)','Process OSS (Provision Completed)','Process ISISKA (RWOS)','Completed (PS)']
			respond_to do |format|
				format.html
				format.csv { send_data @orders.to_csv }
				format.xls { send_data @orders.to_csv(col_sep: "\t") }
			end
		end
	end

	def download
		if Order.exists?
			case params[:query]
			when "totalInputHI" 
				@orders = Order.where(orderdate: Date.today).where(sto: params[:datel]).where.not("status in ('CANCEL COMPLETED','Cancel Order')")
			when "totalInputMS2NHI"
				@orders = Order.where(orderdate: Date.today).where(sto: params[:datel]).where(status_va: "VA")
			when "PI>HI"
				@orders = Order.where.not(orderdate: Date.today).where(sto: params[:datel]).where(status_va: "VA").where(status: "Process OSS (Provision Issued)")
			when "PIHI"
				@orders = Order.where(orderdate: Date.today).where(sto: params[:datel]).where(status_va: "VA").where(status: "Process OSS (Provision Issued)")
			when "grandTotal"
				@orders = Order.where(sto: params[:datel]).where(status_va: "VA").where(status: "Process OSS (Provision Issued)")
			when "AC"
				@orders = Order.where(sto: params[:datel]).where(status_va: "VA").where(status: "Process OSS (Activation Completed)")
        # when "PS"
        # @orders = Order.where(orderdate: Date.today).where(sto: params[:datel]).where(status_va: "VA").where(status: "Completed (PS)")
    else
    	@orders = Order.order(:orderdate)
    end
    respond_to do |format|
    	format.html
    	format.csv { send_data @orders.to_csv }
    	format.xls { send_data @orders.to_csv(col_sep: "\t") }
    end
end
end

def show

end
    #def show
      # request_uri = 'https://starclick.telkom.co.id/noss_prod/data/get_order.php?_dc=1471594704134&SearchText=kalteng&Field=ORG&Fieldstatus=&Fieldwitel=&StartDate=&EndDate=&page=1&start=0&limit=10000'
      # request_query = ''
      # url = "#{request_uri}#{request_query}"

      # buffer = open(url).read

      # result = JSON.parse(buffer)

      # @data = result["order"]

      #@results = result.kalteng(5)
    #end

    def starclick

    	request_uri = 'https://starclick.telkom.co.id/noss_prod/data/get_order.php?_dc=1471594704134&SearchText=kalteng&Field=ORG&Fieldstatus=&Fieldwitel=&StartDate=&EndDate=&page=1&start=0&limit=10'
    	request_query = ''
    	url = "#{request_uri}#{request_query}"

    	buffer = open(url).read

    	result = JSON.parse(buffer)

    	data = result["order"]

    	out = 0
    	update = 0
    	baru = 0

    	data.each do |row|  

    		if row
    			product = Order.new

    			product.sc = row["orderId"]
    			product.orderdate = row["orderDate"].to_date
    			product.ncli = row["orderNcli"]
    			product.customer = row["orderName"]
    			product.address = row["orderAddr"]
    			product.nd_internet = row["ndemSpeedy"]
    			product.nd_voice = row["ndemPots"]
    			product.status = row["orderStatus"]
    			product.status_message = row["orderPaket"]
    			product.odp = row["alproName"]
    			product.witel = row["orderPlasa"]
    			product.k_contact = row["kcontact"]
    			product.inputer = row["username"]
    			product.transaction_type = row["jenisPsb"]
    			product.sto = row["sto"]

    			if Order.find_by(sc: product.sc)
    				id = Order.where(sc: product.sc).first.id
    				if Order.where(id: id).first.status == product.status 
    					next
    				else                
    					Order.update(id, status: product.status)
    					Order.update(id, status_message: product.status_message)
    					update += 1   
    				end
    			else
    				baru += 1
    				product.save
    			end
    		else
    			out += 1
    			next
    		end
    	end

    	redirect_to root_url, notice: "Data Update : #{update}, Baru : #{baru} & Out : #{out}" 
    end

    def ms2n

    	@page = Nokogiri::HTML(open("http://mydashboard.telkom.co.id/ms2/detil_progres_useetv2_.php?sub_chanel=%&chanel=%&p_kawasan=DIVRE_6&witel=KALTENG&indihome=&kode=1&c_witel=43&p_cseg=%&p_etat=4&start_date=01/01/2016&end_date=31/12/2016&indihome=&migrasi=&starclick=&plblcl=&inden=&status_order=VA"))   
      #puts page.class   # => Nokogiri::HTML::Document

      update = 0

      @page.css("table tr[bgcolor='']").each do |el|

      	ncli_ms2n = el.css("td")[4].text
      	status_ms2n = el.css("td")[6].text

      	if Order.find_by(ncli: ncli_ms2n)
      		id = Order.where(ncli: ncli_ms2n).first.id

      		if Order.where(id: id).first.status_va == "VA"
            #Order.update(id, statusVA: nil)
            #update += 1
            next
        else                 
        	Order.update(id, status_va: status_ms2n)
        	update += 1   
        end

    else
    	next
    end

end
redirect_to root_url, notice: "Data Update VA: #{update}", class: "bg-danger"
end

def import
	Order.import(params[:file])
  		# after the import, redirect and let us know the method worked!
  		redirect_to root_url, notice: "Activity Data Imported!"
  	end

  end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_dashboard1.html.erb
<div id="dashboard1" class="row">
	<% @statuses.each do |status| %>
		<div class="col-md-4">
			<div>
				<p>
					<span>
						<%= status %><br>					
					</span>
					<span>
						3P: <%= Order.where(status: status).where(status_va: "VA").count %><br>
						Non 3P: <%= Order.where(status: status).where(status_va: nil).count %>
					</span>
				</p>
			</div>
		</div>	
	<% end %>
</div>

app/views/orders/_dashboard2.html.erb
<div id="dashboard2" class="row">
	<div class="col-md-12">
		<table id="dashboard-table" border="1">
			<thead bgcolor="red">
				<tr>
					<th rowspan="3">Area</th>
					<th rowspan="3">Total Inputan HI</th>
					<th rowspan="3">Total Inputan Masuk MS2N</th>
					<th colspan="3">Provision Issued</th>
					<th rowspan="3">Activation Completed</th>
				</tr>
				<tr>
					<th rowspan="2">HI > </th>
					<th rowspan="2">HI</th>
					<th rowspan="2">Grand Total</th>
				</tr>
			</thead>
			<tbody>
				<% if @sto == nil %>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				<% else %>
					<% @sto.each do |datel|%>
					<tr>
						<% case datel %>
						<% when ['KKN','KKP','PLK','PPS','PYM'] %>
						<td bgcolor="orange"> PLK </td>
						<% when ['KMI','SUA','PBU'] %>
						<td bgcolor="orange"> PBU </td>
						<% when ['KPB','SAI'] %>
						<td bgcolor="orange"> SAI </td>
						<% when ['AMP','PRC','BNT','TML','MTW'] %>
						<td bgcolor="orange"> MTW </td>
						<% when ['KKN','KKP','PLK','PPS','PYM','KMI','SUA','PBU','KPB','SAI','AMP','PRC','BNT','TML','MTW'] %>
						<td bgcolor="lightblue"> TOTAL </td>
						<% else %>			
						<td><%= datel %></td>
						<% end %>
						<td><%= link_to Order.where(orderdate: Date.today).where(sto: datel).where.not("status in ('CANCEL COMPLETED','Cancel Order')").count, download_url(format: "xls", query: "totalInputHI", datel: datel) %></td>

						<td><%= link_to Order.where(orderdate: Date.today).where(sto: datel).where(status_va: "VA").count, download_url(format: "xls", query: "totalInputMS2NHI", datel: datel) %></td>

						<td><%= link_to Order.where.not(orderdate: Date.today).where(sto: datel).where(status_va: "VA").where(status: "Process OSS (Provision Issued)").count, download_url(format: "xls", query: "PI>HI", datel: datel) %></td>

						<td><%= link_to Order.where(orderdate: Date.today).where(sto: datel).where(status_va: "VA").where(status: "Process OSS (Provision Issued)").count, download_url(format: "xls", query: "PIHI", datel: datel) %></td>

						<td><%= link_to Order.where(sto: datel).where(status_va: "VA").where(status: "Process OSS (Provision Issued)").count, download_url(format: "xls", query: "grandTotal", datel: datel) %></td>

						<td><%= link_to Order.where(sto: datel).where(status_va: "VA").where(status: "Process OSS (Activation Completed)").count, download_url(format: "xls", query: "AC", datel: datel) %></td>
					</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>	
</div>

app/views/orders/_show.html.erb
<div id="showData">
	<table>
		<thead>
			<tr>
				<th>SC</th>
				<th>Tanggal Order</th>
				<th>NCLI</th>
				<th>Pelanggan</th>
				<th>Alamat</th>
				<th>ND Inet</th>
				<th>ND Voice</th>
				<th>Witel</th>
				<th>STO</th>
				<th>ODP</th>
				<th>Status</th>
				<th>Status Message</th>
				<th>K Kontak</th>
				<th>ID Inputer</th>
				<th>Tipe Transaksi</th>
			</tr>
		</thead>
		<tbody>

		</tbody>
	</table>
</div>

app/views/orders/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Dashboard</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<div class="container">
		<div>
			<%= flash[:notice] %><br>
			<b>Total Data Witel Kalteng :</b> <%= Order.count %><br>
			<b>Today :</b> <%= Date.today %>
		</div>
		<hr>
		<br>
		<%= render(:partial => "dashboard1") %>
		<%= render(:partial => "dashboard2") %>
		<br><br>	
		<hr>		
		<div class="row">
			<div class="col-md-6">
				<h4>Import data</h4>

				<%= link_to "Import Starclick", starclick_url %> |
				<%= link_to "Combine to MS2N", ms2n_url %>

				<h4>Export Data</h4>
				Download:
				<%= link_to "CSV", orders_path(format: "csv") %> |
				<%= link_to "Excel", orders_path(format: "xls") %>
			</div>

			<div class="col-md-6" style="margin-bottom: 100px">
				<%= form_tag import_orders_path, multipart: true do %>
				<%= file_field_tag :file %>
				<%= submit_tag "Import" %>
				<% end %>
			</div>
		</div>	
	</div>
</body>
</html>